"""add incoming attachment table

Revision ID: 16f36aff3c70
Revises: b406bd357742
Create Date: 2026-05-08 10:40:25.846087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f36aff3c70'
down_revision: Union[str, Sequence[str], None] = 'b406bd357742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['cchub_announcements.incoming_emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cchub_announcements'
    )
    op.create_index(op.f('ix_cchub_announcements_email_attachments_email_id'), 'email_attachments', ['email_id'], unique=False, schema='cchub_announcements')
    op.create_index(op.f('ix_cchub_announcements_email_attachments_id'), 'email_attachments', ['id'], unique=False, schema='cchub_announcements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cchub_announcements_email_attachments_id'), table_name='email_attachments', schema='cchub_announcements')
    op.drop_index(op.f('ix_cchub_announcements_email_attachments_email_id'), table_name='email_attachments', schema='cchub_announcements')
    op.drop_table('email_attachments', schema='cchub_announcements')
    # ### end Alembic commands ###
