"""add EmailStatusEnum

Revision ID: 230c6b7f1e5a
Revises: 04e7a7214e6a
Create Date: 2026-05-18 16:32:41.810830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230c6b7f1e5a'
down_revision: Union[str, Sequence[str], None] = '04e7a7214e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
