"""add ai_emails table

Revision ID: 3ee8a2270ec2
Revises: 16f36aff3c70
Create Date: 2026-05-12 14:38:03.046490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee8a2270ec2'
down_revision: Union[str, Sequence[str], None] = '16f36aff3c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('ai_email', sa.Text(), nullable=True),
    sa.Column('in_knowledge_base', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['cchub_announcements.incoming_emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cchub_announcements'
    )
    op.create_index(op.f('ix_cchub_announcements_ai_emails_email_id'), 'ai_emails', ['email_id'], unique=False, schema='cchub_announcements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cchub_announcements_ai_emails_email_id'), table_name='ai_emails', schema='cchub_announcements')
    op.drop_table('ai_emails', schema='cchub_announcements')
    # ### end Alembic commands ###
