"""add title to ai_emails table

Revision ID: 9749867a2efc
Revises: c798fcfd3c23
Create Date: 2026-05-18 09:08:14.519642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9749867a2efc'
down_revision: Union[str, Sequence[str], None] = 'c798fcfd3c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_emails', sa.Column('ai_title', sa.Text(), nullable=True), schema='cchub_announcements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_emails', 'ai_title', schema='cchub_announcements')
    # ### end Alembic commands ###
