"""create tables

Revision ID: 8f499bdab7fa
Revises:
Create Date: 2026-04-23 16:16:16.134534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f499bdab7fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('TECH_QUESTION', 'CHANGE', 'NEW', 'REVOKED', name='announcementcategoryenum'), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('resource_link', sa.String(length=500), nullable=True),
    sa.Column('script_kz', sa.Text(), nullable=True),
    sa.Column('script_ru', sa.Text(), nullable=True),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('revoked_link', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cchub_announcements'
    )
    op.create_index(op.f('ix_cchub_announcements_announcements_id'), 'announcements', ['id'], unique=False, schema='cchub_announcements')
    op.create_table('announcement_read_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['cchub_announcements.announcements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'announcement_id', name='uq_user_announcement'),
    schema='cchub_announcements'
    )
    op.create_index(op.f('ix_cchub_announcements_announcement_read_status_id'), 'announcement_read_status', ['id'], unique=False, schema='cchub_announcements')
    op.create_index(op.f('ix_cchub_announcements_announcement_read_status_user_id'), 'announcement_read_status', ['user_id'], unique=False, schema='cchub_announcements')
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['cchub_announcements.announcements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cchub_announcements'
    )
    op.create_index(op.f('ix_cchub_announcements_attachments_announcement_id'), 'attachments', ['announcement_id'], unique=False, schema='cchub_announcements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cchub_announcements_attachments_announcement_id'), table_name='attachments', schema='cchub_announcements')
    op.drop_table('attachments', schema='cchub_announcements')
    op.drop_index(op.f('ix_cchub_announcements_announcement_read_status_user_id'), table_name='announcement_read_status', schema='cchub_announcements')
    op.drop_index(op.f('ix_cchub_announcements_announcement_read_status_id'), table_name='announcement_read_status', schema='cchub_announcements')
    op.drop_table('announcement_read_status', schema='cchub_announcements')
    op.drop_index(op.f('ix_cchub_announcements_announcements_id'), table_name='announcements', schema='cchub_announcements')
    op.drop_table('announcements', schema='cchub_announcements')
    # ### end Alembic commands ###
