"""add incoming email tables

Revision ID: b406bd357742
Revises: 8f499bdab7fa
Create Date: 2026-05-06 15:46:10.491425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b406bd357742'
down_revision: Union[str, Sequence[str], None] = '8f499bdab7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incoming_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outlook_id', sa.String(length=500), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'GREEN', 'RED', 'YELLOW', 'GRAY', name='emailstatusenum'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outlook_id'),
    schema='cchub_announcements'
    )
    op.create_index(op.f('ix_cchub_announcements_incoming_emails_id'), 'incoming_emails', ['id'], unique=False, schema='cchub_announcements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cchub_announcements_incoming_emails_id'), table_name='incoming_emails', schema='cchub_announcements')
    op.drop_table('incoming_emails', schema='cchub_announcements')
    # ### end Alembic commands ###
