"""add scripts RU, KZ to ai_emails table

Revision ID: c798fcfd3c23
Revises: 3ee8a2270ec2
Create Date: 2026-05-13 10:20:15.642878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c798fcfd3c23'
down_revision: Union[str, Sequence[str], None] = '3ee8a2270ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_emails', sa.Column('script_ru', sa.Text(), nullable=True), schema='cchub_announcements')
    op.add_column('ai_emails', sa.Column('script_kz', sa.Text(), nullable=True), schema='cchub_announcements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_emails', 'script_kz', schema='cchub_announcements')
    op.drop_column('ai_emails', 'script_ru', schema='cchub_announcements')
    # ### end Alembic commands ###
