"""add column

Revision ID: cc041b291933
Revises: a1b2c3d4e5f6
Create Date: 2026-05-21 11:48:23.605125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc041b291933'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_emails', sa.Column('ai_summary', sa.Text(), nullable=True), schema='cchub_announcements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_emails', 'ai_summary', schema='cchub_announcements')
    # ### end Alembic commands ###
