"""add columns is_ai and source

Revision ID: eb3c1ed522b8
Revises: 230c6b7f1e5a
Create Date: 2026-05-19 11:08:00.558936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3c1ed522b8'
down_revision: Union[str, Sequence[str], None] = '230c6b7f1e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('is_ai', sa.Boolean(), nullable=True), schema='cchub_announcements')
    op.add_column('announcements', sa.Column('source', sa.String(length=50), nullable=True), schema='cchub_announcements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'source', schema='cchub_announcements')
    op.drop_column('announcements', 'is_ai', schema='cchub_announcements')
    # ### end Alembic commands ###
